### ISSUE TITLE
List UoM as the Data Controller for WorkflowHub

### ISSUE THREAD

**Issue by stain** [workflowhub-eu/about#16]
https://workflowhub.eu/home/terms says
>  The Data Controller for the WorkflowHub is EOSC-Life WorkflowHub work package, contact at workflowhub-admin@listserv.manchester.ac.uk. If the WorkflowHub is accessed at a different URL, the data controller is likely someone else

but the GDPR regulations says
>  ‘controller’ means the natural or legal person, public authority, agency or other body which, alone or jointly with others, determines the purposes and means of the processing of personal data; where the purposes and means of such processing are determined by Union or Member State law, the controller or the specific criteria for its nomination may be provided for by Union or Member State law;

_EOSC-Life WorkflowHub work package_ is not the correct work package name, and in addition a work package is not a natural or legal person. Do we want to claim it as an “other body”? Another problem is that the contact list given does not go to the work package or work package leaders.

I suggest to list **The University of Manchester, UK** as the legal entity that is the Data Controller, as employers of the individuals of that list, and as the formal consortium agreement member of EOSC-Life and the hosting provider of the virtual machine that runs the `workflowhub.eu` instance. So effectively UoM is already the data controller.

The controller has legal responsibilities, so to avoid individuals working on this potentially be legally responsible, it should be the employer, as the legal entity, that is the _Data Controller_

**Comment by stain** [comment]
One caveat is that the domain name `workflowhub.eu` is not controlled by UoM, but I don't believe that would be a legal requirement on the data controller, just like they are not required to own their physical premises.

**Comment by stuzart** [comment]
it needs to be contact point, person, agency or organisation, who knows about how the data is used, and can remove data if requested. That wouldn't be University of Manchester. I can't think who it could be other than the WP. Perhaps it should be joint controllers together with uniman or eosc-life

**Comment by stuzart** [comment]
it could be perhaps be phrased as "the Work Package, acting under the repsonsibility of The Uni Man"

**Comment by alaninmcr** [comment]
I wonder if this should be an explicit part of the configuration of a FAIRDOM-SEEK instance.

**Comment by floradanna** [comment]
If by Data Controller you mean "who is responsible for the content that users upload in FAIRDOMHub", it should be the user himself/herself, as clarified in Terms and Conditions (T&C).
However, T&C say that if inappropriate content is detected, the provider can remove the content completely or partly.

If by Data Controller you mean "who is responsible for the personal data of registered/non-registered users" instead, it should be FAIRDOMHub legal entity (which is HITS gGmbH ?). https://fairdomhub.org/home/imprint

**Comment by fbacall** [comment]
TeSS says:
![image](https://user-images.githubusercontent.com/503373/124729172-1e899e80-df08-11eb-889e-f05a991c3ec5.png)

(although we probably need to update the address)

**Comment by fbacall** [comment]
Updated here

https://workflowhub.eu/home/terms

> The data controller for WorkflowHub is The University of Manchester.
> 
> If WorkflowHub is accessed at a different URL, the data controller is likely someone else.
> You may contact the Data Controller to request access to data about yourself, or to request update or removal of your personally identifiable information.
> 
> 
> For any enquiries or requests, please contact:
> Email: [admins@esciencelab.org.uk](mailto:admins@esciencelab.org.uk)
> Post:
> WorkflowHub Team, eScience Lab
> c/o Shoaib Sufi,
> Room 2.70 Dept. of Computer Science,
> Kilburn Building,
> Oxford Road,
> Manchester,
> M13 9PL
