### ISSUE TITLE
Issue on page: Adding files

### ISSUE THREAD

**Issue by mr-c** [workflowhub-eu/about#34]
I would like to report an issue on the Adding files page at `/docs/adding-files/`. Description of the issue:

Under https://about.workflowhub.eu/docs/adding-files/#upload--import-a-local-file & https://about.workflowhub.eu/docs/adding-files/#git
"Abstract CWL" link does not seem to work: https://about.workflowhub.eu/docs/adding-files/#bookmark=id.9p7blcbntfn5

**Comment by fbacall** [comment]
Thanks for reporting this (and the other issue). Looks like some artefact of the conversion from Google docs > Markdown
